/* eslint-disable */
/* prettier-ignore */

/**
 * Generated by @zyntra-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Zyntra router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2026-02-06T19:22:17.040Z
 * Framework: generic
 * Output: src/
 */

// Generated by @zyntra-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "user": {
      "name": "user",
      "path": "/user",
      "description": "User management endpoints for handling user data.",
      "actions": {
        "list": {
          "name": "List",
          "description": "List all users currently registered in the system.",
          "path": "",
          "use": [
            {
              "name": "UserProcedure"
            }
          ],
          "method": "GET",
          "$Infer": {}
        },
        "getById": {
          "name": "GetById",
          "description": "Fetch a single user's details using their unique identifier.",
          "path": ":id",
          "use": [
            {
              "name": "UserProcedure"
            }
          ],
          "method": "GET",
          "$Infer": {}
        },
        "create": {
          "name": "Create",
          "type": "mutation",
          "path": "",
          "method": "POST",
          "description": "Register a new user in the system.",
          "use": [
            {
              "name": "UserProcedure"
            }
          ],
          "$Infer": {},
          "bodySchema": {}
        },
        "update": {
          "name": "Update",
          "type": "mutation",
          "path": ":id",
          "method": "PUT",
          "description": "Modify an existing user's details.",
          "use": [
            {
              "name": "UserProcedure"
            }
          ],
          "$Infer": {},
          "bodySchema": {}
        },
        "delete": {
          "name": "Delete",
          "type": "mutation",
          "path": ":id",
          "method": "DELETE",
          "description": "Permanently delete a user from the system.",
          "use": [
            {
              "name": "UserProcedure"
            }
          ],
          "$Infer": {}
        }
      }
    },
    "post": {
      "name": "post",
      "path": "/post",
      "description": "Post management endpoints for handling post data.",
      "actions": {
        "list": {
          "name": "List",
          "description": "List all posts currently registered in the system.",
          "path": "",
          "use": [
            {
              "name": "PostProcedure"
            }
          ],
          "method": "GET",
          "$Infer": {}
        },
        "getById": {
          "name": "GetById",
          "description": "Fetch a single post's details using their unique identifier.",
          "path": ":id",
          "use": [
            {
              "name": "PostProcedure"
            }
          ],
          "method": "GET",
          "$Infer": {}
        },
        "create": {
          "name": "Create",
          "type": "mutation",
          "path": "",
          "method": "POST",
          "description": "Register a new post in the system.",
          "use": [
            {
              "name": "PostProcedure"
            }
          ],
          "$Infer": {},
          "bodySchema": {}
        },
        "update": {
          "name": "Update",
          "type": "mutation",
          "path": ":id",
          "method": "PUT",
          "description": "Modify an existing post's details.",
          "use": [
            {
              "name": "PostProcedure"
            }
          ],
          "$Infer": {},
          "bodySchema": {}
        },
        "delete": {
          "name": "Delete",
          "type": "mutation",
          "path": ":id",
          "method": "DELETE",
          "description": "Permanently delete a post from the system.",
          "use": [
            {
              "name": "PostProcedure"
            }
          ],
          "$Infer": {}
        }
      }
    },
    "comment": {
      "name": "comment",
      "path": "/comment",
      "description": "Comment management endpoints for handling comment data.",
      "actions": {
        "list": {
          "name": "List",
          "description": "List all comments currently registered in the system.",
          "path": "",
          "use": [
            {
              "name": "CommentProcedure"
            }
          ],
          "method": "GET",
          "$Infer": {}
        },
        "getById": {
          "name": "GetById",
          "description": "Fetch a single comment's details using their unique identifier.",
          "path": ":id",
          "use": [
            {
              "name": "CommentProcedure"
            }
          ],
          "method": "GET",
          "$Infer": {}
        },
        "create": {
          "name": "Create",
          "type": "mutation",
          "path": "",
          "method": "POST",
          "description": "Register a new comment in the system.",
          "use": [
            {
              "name": "CommentProcedure"
            }
          ],
          "$Infer": {},
          "bodySchema": {}
        },
        "update": {
          "name": "Update",
          "type": "mutation",
          "path": ":id",
          "method": "PUT",
          "description": "Modify an existing comment's details.",
          "use": [
            {
              "name": "CommentProcedure"
            }
          ],
          "$Infer": {},
          "bodySchema": {}
        },
        "delete": {
          "name": "Delete",
          "type": "mutation",
          "path": ":id",
          "method": "DELETE",
          "description": "Permanently delete a comment from the system.",
          "use": [
            {
              "name": "CommentProcedure"
            }
          ],
          "$Infer": {}
        }
      }
    }
  },
  "docs": {
    "openapi": {
      "openapi": "3.0.0",
      "info": {
        "title": "Zyntra.js Starter (Bun REST API)",
        "version": "1.0.0",
        "description": "A sample Bun REST API built with Zyntra.js"
      },
      "servers": [
        {
          "url": "http://localhost:3000/api/v1",
          "description": "Default server"
        }
      ],
      "tags": [
        {
          "name": "Example"
        }
      ],
      "paths": {
        "/example": {
          "get": {
            "summary": "health",
            "operationId": "health",
            "tags": [
              "Example"
            ],
            "parameters": [],
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          }
        }
      },
      "components": {
        "schemas": {},
        "securitySchemes": {}
      }
    },
    "info": {
      "title": "Zyntra.js Starter (Bun REST API)",
      "version": "1.0.0",
      "description": "A sample Bun REST API built with Zyntra.js"
    }
  }
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
